server:
  port: 8080

  servlet:
    contextPath: /rest/api

spring:
  application.name: gateway
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

eureka:
  client:
    register-with-eureka: false