server:
  port: 8082

  servlet:
    contextPath: /rest/itinerary

spring:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: create

  datasource:
    url: jdbc:h2:mem:spring
    username: sa
    password:
    initialization-mode: always
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false

discovery:
  hostname:
    host: localhost
    port: 5000
    context: /rest/discovery
    endpoint: /subscribe

  payload:
    tags: itinerary, passenger

logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG